/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthRegisterRouteRouteImport } from './routes/_auth/register/route'
import { Route as AuthProfileRouteRouteImport } from './routes/_auth/profile/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as publicTasksRouteRouteImport } from './routes/(public)/tasks/route'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileRouteRoute = AuthProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const publicTasksRouteRoute = publicTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/tasks': typeof publicTasksRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/profile': typeof AuthProfileRouteRouteWithChildren
  '/register': typeof AuthRegisterRouteRoute
  '/profile/': typeof AuthProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/tasks': typeof publicTasksRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/profile': typeof AuthProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/(public)/tasks': typeof publicTasksRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/profile': typeof AuthProfileRouteRouteWithChildren
  '/_auth/register': typeof AuthRegisterRouteRoute
  '/(public)/': typeof publicIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks' | '/login' | '/profile' | '/register' | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks' | '/login' | '/register' | '/profile'
  id:
    | '__root__'
    | '/(public)'
    | '/_auth'
    | '/(public)/tasks'
    | '/_auth/login'
    | '/_auth/profile'
    | '/_auth/register'
    | '/(public)/'
    | '/_auth/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(public)/tasks': {
      id: '/(public)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof publicTasksRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicTasksRouteRoute: typeof publicTasksRouteRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicTasksRouteRoute: publicTasksRouteRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AuthProfileRouteRouteChildren {
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
}

const AuthProfileRouteRouteChildren: AuthProfileRouteRouteChildren = {
  AuthProfileIndexRoute: AuthProfileIndexRoute,
}

const AuthProfileRouteRouteWithChildren =
  AuthProfileRouteRoute._addFileChildren(AuthProfileRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthProfileRouteRoute: typeof AuthProfileRouteRouteWithChildren
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthProfileRouteRoute: AuthProfileRouteRouteWithChildren,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
