/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedProfileRouteRouteImport } from './routes/_protected/profile/route'
import { Route as AuthRegisterRouteRouteImport } from './routes/_auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as ProtectedTasksIndexRouteImport } from './routes/_protected/tasks/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedTasksTaskIdIndexRouteImport } from './routes/_protected/tasks/$taskId/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedProfileRouteRoute = ProtectedProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedTasksIndexRoute = ProtectedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProfileRouteRoute,
} as any)
const ProtectedTasksTaskIdIndexRoute =
  ProtectedTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/profile': typeof ProtectedProfileRouteRouteWithChildren
  '/profile/': typeof ProtectedProfileIndexRoute
  '/tasks/': typeof ProtectedTasksIndexRoute
  '/tasks/$taskId/': typeof ProtectedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRouteRoute
  '/register': typeof AuthRegisterRouteRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/tasks': typeof ProtectedTasksIndexRoute
  '/tasks/$taskId': typeof ProtectedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/register': typeof AuthRegisterRouteRoute
  '/_protected/profile': typeof ProtectedProfileRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/tasks/': typeof ProtectedTasksIndexRoute
  '/_protected/tasks/$taskId/': typeof ProtectedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/profile/'
    | '/tasks/'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/profile' | '/tasks' | '/tasks/$taskId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/profile'
    | '/_public/'
    | '/_protected/profile/'
    | '/_protected/tasks/'
    | '/_protected/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/tasks/': {
      id: '/_protected/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ProtectedTasksIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedProfileRouteRoute
    }
    '/_protected/tasks/$taskId/': {
      id: '/_protected/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof ProtectedTasksTaskIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedProfileRouteRouteChildren {
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedProfileRouteRouteChildren: ProtectedProfileRouteRouteChildren = {
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedProfileRouteRouteWithChildren =
  ProtectedProfileRouteRoute._addFileChildren(
    ProtectedProfileRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedProfileRouteRoute: typeof ProtectedProfileRouteRouteWithChildren
  ProtectedTasksIndexRoute: typeof ProtectedTasksIndexRoute
  ProtectedTasksTaskIdIndexRoute: typeof ProtectedTasksTaskIdIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedProfileRouteRoute: ProtectedProfileRouteRouteWithChildren,
  ProtectedTasksIndexRoute: ProtectedTasksIndexRoute,
  ProtectedTasksTaskIdIndexRoute: ProtectedTasksTaskIdIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
